# PRUEBA_INFINITY

﻿(01) CANTIDAD,(02) PAIS,(03) ESTADO,(04) MUNICIPIO
13,MÉXICO,AGUASCALIENTES,AGUASCALIENTES
1,MÉXICO,AGUASCALIENTES,PABELLON DE ARTEAGA
4,MÉXICO,AGUASCALIENTES,TEPEZALA
7,MÉXICO,AGUASCALIENTES,SAN FRANCISCO DE LOS ROMO
2,MÉXICO,BAJA CALIFORNIA,ENSENADA
1,MÉXICO,BAJA CALIFORNIA,TECATE
3,MÉXICO,BAJA CALIFORNIA,TIJUANA
6,MÉXICO,BAJA CALIFORNIA SUR,LOS CABOS
7,MÉXICO,CAMPECHE,CALKINI
84,MÉXICO,CAMPECHE,CAMPECHE
179,MÉXICO,CAMPECHE,CARMEN
993,MÉXICO,CAMPECHE,CHAMPOTON
18,MÉXICO,CAMPECHE,HECELCHAKAN
17,MÉXICO,CAMPECHE,HOPELCHEN
4,MÉXICO,CAMPECHE,TENABO
2,MÉXICO,CAMPECHE,ESCARCEGA
2,MÉXICO,CAMPECHE,CALAKMUL
122,MÉXICO,CAMPECHE,SEYBAPLAYA
1,MÉXICO,COLIMA,CUAUHTEMOC
24,MÉXICO,CHIAPAS,ACACOYAGUA
143,MÉXICO,CHIAPAS,ACALA
19,MÉXICO,CHIAPAS,ANGEL ALBINO CORZO
143,MÉXICO,CHIAPAS,ARRIAGA
281,MÉXICO,CHIAPAS,BERRIOZABAL
1,MÉXICO,CHIAPAS,BOCHIL
98,MÉXICO,CHIAPAS,CINTALAPA
8,MÉXICO,CHIAPAS,COMITAN DE DOMINGUEZ
78,MÉXICO,CHIAPAS,LA CONCORDIA
17,MÉXICO,CHIAPAS,COPAINALA
161,MÉXICO,CHIAPAS,CHIAPA DE CORZO
24,MÉXICO,CHIAPAS,CHIAPILLA
27,MÉXICO,CHIAPAS,CHILON
4,MÉXICO,CHIAPAS,ESCUINTLA
1,MÉXICO,CHIAPAS,FRONTERA COMALAPA
2,MÉXICO,CHIAPAS,HUIXTLA
1,MÉXICO,CHIAPAS,IXHUATAN
1,MÉXICO,CHIAPAS,IXTACOMITAN
30,MÉXICO,CHIAPAS,IXTAPA
123,MÉXICO,CHIAPAS,JIQUIPILAS
2,MÉXICO,CHIAPAS,JITOTOL
1,MÉXICO,CHIAPAS,JUAREZ
1,MÉXICO,CHIAPAS,LARRAINZAR
35,MÉXICO,CHIAPAS,MAPASTEPEC
1,MÉXICO,CHIAPAS,LAS MARGARITAS
1,MÉXICO,CHIAPAS,MAZATAN
3,MÉXICO,CHIAPAS,MOTOZINTLA
6,MÉXICO,CHIAPAS,OCOSINGO
249,MÉXICO,CHIAPAS,OCOZOCOAUTLA DE ESPINOSA
15,MÉXICO,CHIAPAS,OSTUACAN
1,MÉXICO,CHIAPAS,PANTEPEC
2,MÉXICO,CHIAPAS,PICHUCALCO
40,MÉXICO,CHIAPAS,PIJIJIAPAN
3,MÉXICO,CHIAPAS,VILLA COMALTITLAN
2,MÉXICO,CHIAPAS,PUEBLO NUEVO SOLISTAHUACAN
1,MÉXICO,CHIAPAS,RAYON
3,MÉXICO,CHIAPAS,REFORMA
9,MÉXICO,CHIAPAS,SAN CRISTOBAL DE LAS CASAS
39,MÉXICO,CHIAPAS,SAN FERNANDO
15,MÉXICO,CHIAPAS,SOYALO
144,MÉXICO,CHIAPAS,SUCHIAPA
13,MÉXICO,CHIAPAS,TAPACHULA
1,MÉXICO,CHIAPAS,TAPILULA
93,MÉXICO,CHIAPAS,TECPATAN
6,MÉXICO,CHIAPAS,TEOPISCA
1023,MÉXICO,CHIAPAS,TONALA
30,MÉXICO,CHIAPAS,TOTOLAPA
5,MÉXICO,CHIAPAS,LA TRINITARIA
12,MÉXICO,CHIAPAS,TUMBALA
784,MÉXICO,CHIAPAS,TUXTLA GUTIERREZ
38,MÉXICO,CHIAPAS,VENUSTIANO CARRANZA
91,MÉXICO,CHIAPAS,VILLA CORZO
189,MÉXICO,CHIAPAS,VILLAFLORES
7,MÉXICO,CHIAPAS,ZINACANTAN
36,MÉXICO,CHIAPAS,EMILIANO ZAPATA
9,MÉXICO,CIUDAD DE MÉXICO,AZCAPOTZALCO
8,MÉXICO,CIUDAD DE MÉXICO,COYOACAN
8,MÉXICO,CIUDAD DE MÉXICO,CUAJIMALPA DE MORELOS
9,MÉXICO,CIUDAD DE MÉXICO,GUSTAVO A. MADERO
3,MÉXICO,CIUDAD DE MÉXICO,IZTACALCO
14,MÉXICO,CIUDAD DE MÉXICO,IZTAPALAPA
5,MÉXICO,CIUDAD DE MÉXICO,LA MAGDALENA CONTRERAS
1,MÉXICO,CIUDAD DE MÉXICO,MILPA ALTA
13,MÉXICO,CIUDAD DE MÉXICO,ALVARO OBREGON
7,MÉXICO,CIUDAD DE MÉXICO,TLALPAN
2,MÉXICO,CIUDAD DE MÉXICO,XOCHIMILCO
7,MÉXICO,CIUDAD DE MÉXICO,BENITO JUAREZ
10,MÉXICO,CIUDAD DE MÉXICO,CUAUHTEMOC
8,MÉXICO,CIUDAD DE MÉXICO,MIGUEL HIDALGO
3,MÉXICO,CIUDAD DE MÉXICO,VENUSTIANO CARRANZA
3,MÉXICO,GUANAJUATO,LEON
4762,MÉXICO,GUERRERO,ACAPULCO DE JUAREZ
44,MÉXICO,GUERRERO,ATOYAC DE ALVAREZ
7,MÉXICO,GUERRERO,AYUTLA DE LOS LIBRES
666,MÉXICO,GUERRERO,AZOYU
55,MÉXICO,GUERRERO,BENITO JUAREZ
4,MÉXICO,GUERRERO,COPALA
1,MÉXICO,GUERRERO,COPANATOYAC
117,MÉXICO,GUERRERO,COYUCA DE BENITEZ
435,MÉXICO,GUERRERO,CUAJINICUILAPA
3,MÉXICO,GUERRERO,CUAUTEPEC
2,MÉXICO,GUERRERO,CHILAPA DE ALVAREZ
21,MÉXICO,GUERRERO,CHILPANCINGO DE LOS BRAVO
6,MÉXICO,GUERRERO,FLORENCIO VILLARREAL
4,MÉXICO,GUERRERO,HUITZUCO DE LOS FIGUEROA
6,MÉXICO,GUERRERO,IGUALA DE LA INDEPENDENCIA
232,MÉXICO,GUERRERO,IGUALAPA
3,MÉXICO,GUERRERO,JOSE AZUETA
5,MÉXICO,GUERRERO,JUAN R. ESCUDERO
1,MÉXICO,GUERRERO,MALINALTEPEC
1,MÉXICO,GUERRERO,MARTIR DE CUILAPAN
6,MÉXICO,GUERRERO,METLATONOC
3437,MÉXICO,GUERRERO,OMETEPEC
57,MÉXICO,GUERRERO,SAN LUIS ACATLAN
23,MÉXICO,GUERRERO,SAN MARCOS
9,MÉXICO,GUERRERO,TECOANAPA
18,MÉXICO,GUERRERO,TECPAN DE GALEANA
1,MÉXICO,GUERRERO,TEPECOACUILCO DE TRUJANO
1,MÉXICO,GUERRERO,TIXTLA DE GUERRERO
607,MÉXICO,GUERRERO,TLACOACHISTLAHUACA
531,MÉXICO,GUERRERO,XOCHISTLAHUACA
61,MÉXICO,GUERRERO,MARQUELIA
5,MÉXICO,GUERRERO,COCHOAPA EL GRANDE
101,MÉXICO,GUERRERO,JUCHITAN
1,MÉXICO,GUERRERO,ILIATENCO
20,MÉXICO,HIDALGO,ACTOPAN
2,MÉXICO,HIDALGO,ALMOLOYA
1,MÉXICO,HIDALGO,APAN
1,MÉXICO,HIDALGO,EPAZOYUCAN
1,MÉXICO,HIDALGO,METEPEC
1,MÉXICO,HIDALGO,SAN AGUSTIN METZQUITITLAN
10,MÉXICO,HIDALGO,PACHUCA DE SOTO
3,MÉXICO,HIDALGO,MINERAL DE LA REFORMA
3,MÉXICO,HIDALGO,TEPEAPULCO
32,MÉXICO,HIDALGO,TEZONTEPEC DE ALDAMA
1,MÉXICO,HIDALGO,TIZAYUCA
1,MÉXICO,HIDALGO,TULA DE ALLENDE
1,MÉXICO,HIDALGO,TULANCINGO DE BRAVO
24,MÉXICO,HIDALGO,ZEMPOALA
1,MÉXICO,JALISCO,AHUALULCO DE MERCADO
2,MÉXICO,JALISCO,AMECA
1,MÉXICO,JALISCO,ATOTONILCO EL ALTO
2,MÉXICO,JALISCO,LA BARCA
1,MÉXICO,JALISCO,COCULA
262,MÉXICO,JALISCO,CHAPALA
324,MÉXICO,JALISCO,GUADALAJARA
16,MÉXICO,JALISCO,IXTLAHUACAN DE LOS MEMBRILLOS
7,MÉXICO,JALISCO,JAMAY
3,MÉXICO,JALISCO,JOCOTEPEC
1,MÉXICO,JALISCO,JUANACATLAN
1,MÉXICO,JALISCO,MAGDALENA
36,MÉXICO,JALISCO,OCOTLAN
857,MÉXICO,JALISCO,PONCITLAN
15,MÉXICO,JALISCO,EL SALTO
27,MÉXICO,JALISCO,TALA
1,MÉXICO,JALISCO,TAPALPA
1,MÉXICO,JALISCO,TEQUILA
1,MÉXICO,JALISCO,TEUCHITLAN
165,MÉXICO,JALISCO,TLAJOMULCO DE ZUÑIGA
62,MÉXICO,JALISCO,TLAQUEPAQUE
86,MÉXICO,JALISCO,TONALA
1,MÉXICO,JALISCO,TOTOTLAN
1,MÉXICO,JALISCO,VILLA CORONA
2,MÉXICO,JALISCO,ZACOALCO DE TORRES
248,MÉXICO,JALISCO,ZAPOPAN
208,MÉXICO,JALISCO,ZAPOTLAN DEL REY
2,MÉXICO,JALISCO,ZAPOTLANEJO
37,MÉXICO,JALISCO,SAN PEDRO TLAQUEPAQUE
3,MÉXICO,MÉXICO,ATIZAPAN DE ZARAGOZA
1,MÉXICO,MÉXICO,ATLACOMULCO
1,MÉXICO,MÉXICO,COACALCO DE BERRIOZABAL
2,MÉXICO,MÉXICO,CHALCO
2,MÉXICO,MÉXICO,CHIAUTLA
1,MÉXICO,MÉXICO,CHICOLOAPAN
6,MÉXICO,MÉXICO,CHIMALHUACAN
13,MÉXICO,MÉXICO,ECATEPEC DE MORELOS
11,MÉXICO,MÉXICO,HUIXQUILUCAN
5,MÉXICO,MÉXICO,IXTAPALUCA
1,MÉXICO,MÉXICO,IXTLAHUACA
2,MÉXICO,MÉXICO,METEPEC
9,MÉXICO,MÉXICO,NAUCALPAN DE JUAREZ
8,MÉXICO,MÉXICO,NEZAHUALCOYOTL
1,MÉXICO,MÉXICO,LA PAZ
4,MÉXICO,MÉXICO,TECAMAC
1,MÉXICO,MÉXICO,TEMAMATLA
1,MÉXICO,MÉXICO,TEMASCALTEPEC
3,MÉXICO,MÉXICO,TEXCOCO
4,MÉXICO,MÉXICO,TLALNEPANTLA DE BAZ
3,MÉXICO,MÉXICO,TOLUCA
2,MÉXICO,MÉXICO,TULTEPEC
1,MÉXICO,MÉXICO,TULTITLAN
2,MÉXICO,MÉXICO,CUAUTITLAN IZCALLI
11,MÉXICO,MÉXICO,VALLE DE CHALCO SOLIDARIDAD
1,MÉXICO,MICHOACÁN,LAZARO CARDENAS
2,MÉXICO,MICHOACÁN,MORELIA
1,MÉXICO,MICHOACÁN,VENUSTIANO CARRANZA
1,MÉXICO,MORELOS,ATLATLAHUCAN
3,MÉXICO,MORELOS,AXOCHIAPAN
22,MÉXICO,MORELOS,AYALA
2,MÉXICO,MORELOS,CUAUTLA
1,MÉXICO,MORELOS,CUERNAVACA
1,MÉXICO,MORELOS,JIUTEPEC
28,MÉXICO,MORELOS,JOJUTLA
1,MÉXICO,MORELOS,MAZATEPEC
1,MÉXICO,MORELOS,MIACATLAN
13,MÉXICO,MORELOS,PUENTE DE IXTLA
1,MÉXICO,MORELOS,TEPOZTLAN
2,MÉXICO,MORELOS,TETECALA
8,MÉXICO,MORELOS,TETELA DEL VOLCAN
24,MÉXICO,MORELOS,TLALTIZAPAN DE ZAPATA
23,MÉXICO,MORELOS,TLAQUILTENANGO
8,MÉXICO,MORELOS,XOCHITEPEC
1,MÉXICO,MORELOS,YECAPIXTLA
10,MÉXICO,MORELOS,ZACATEPEC
1,MÉXICO,NUEVO LEÓN,APODACA
1,MÉXICO,NUEVO LEÓN,GARCIA
1,MÉXICO,NUEVO LEÓN,GUADALUPE
1,MÉXICO,NUEVO LEÓN,PESQUERIA
1,MÉXICO,NUEVO LEÓN,SANTA CATARINA
8,MÉXICO,OAXACA,ABEJONES
631,MÉXICO,OAXACA,ACATLAN DE PEREZ FIGUEROA
2,MÉXICO,OAXACA,ASUNCION CACALOTEPEC
4,MÉXICO,OAXACA,ASUNCION CUYOTEPEJI
127,MÉXICO,OAXACA,ASUNCION IXTALTEPEC
159,MÉXICO,OAXACA,ASUNCION NOCHIXTLAN
53,MÉXICO,OAXACA,ASUNCION OCOTLAN
15,MÉXICO,OAXACA,ASUNCION TLACOLULITA
187,MÉXICO,OAXACA,AYOTZINTEPEC
84,MÉXICO,OAXACA,EL BARRIO DE LA SOLEDAD
348,MÉXICO,OAXACA,CANDELARIA LOXICHA
286,MÉXICO,OAXACA,CIENEGA DE ZIMATLAN
664,MÉXICO,OAXACA,CIUDAD IXTEPEC
14,MÉXICO,OAXACA,COATECAS ALTAS
4,MÉXICO,OAXACA,COICOYAN DE LAS FLORES
30,MÉXICO,OAXACA,LA COMPAÑIA
28,MÉXICO,OAXACA,CONSTANCIA DEL ROSARIO
46,MÉXICO,OAXACA,COSOLAPA
1,MÉXICO,OAXACA,COSOLTEPEC
2079,MÉXICO,OAXACA,CUILAPAM DE GUERRERO
3,MÉXICO,OAXACA,CUYAMECALCO VILLA DE ZARAGOZA
536,MÉXICO,OAXACA,CHAHUITES
332,MÉXICO,OAXACA,CHALCATONGO DE HIDALGO
1,MÉXICO,OAXACA,CHIQUIHUITLAN DE BENITO JUAREZ
832,MÉXICO,OAXACA,HEROICA CIUDAD DE EJUTLA DE CRESPO
175,MÉXICO,OAXACA,ELOXOCHITLAN DE FLORES MAGON
52,MÉXICO,OAXACA,EL ESPINAL
39,MÉXICO,OAXACA,TAMAZULAPAM DEL ESPIRITU SANTO
321,MÉXICO,OAXACA,GUADALUPE ETLA
8,MÉXICO,OAXACA,GUELATAO DE JUAREZ
4,MÉXICO,OAXACA,GUEVEA DE HUMBOLDT
12,MÉXICO,OAXACA,MESONES HIDALGO
5,MÉXICO,OAXACA,VILLA HIDALGO
1438,MÉXICO,OAXACA,HEROICA CIUDAD DE HUAJUAPAN DE LEON
134,MÉXICO,OAXACA,HUAUTEPEC
3531,MÉXICO,OAXACA,HUAUTLA DE JIMENEZ
71,MÉXICO,OAXACA,IXTLAN DE JUAREZ
362,MÉXICO,OAXACA,HEROICA CIUDAD DE JUCHITAN DE ZARAGOZA
2560,MÉXICO,OAXACA,LOMA BONITA
941,MÉXICO,OAXACA,MAGDALENA APASCO
7,MÉXICO,OAXACA,MAGDALENA JALTEPEC
84,MÉXICO,OAXACA,MAGDALENA MIXTEPEC
93,MÉXICO,OAXACA,MAGDALENA OCOTLAN
13,MÉXICO,OAXACA,MAGDALENA PEÑASCO
59,MÉXICO,OAXACA,MAGDALENA TEITIPAC
102,MÉXICO,OAXACA,MAGDALENA TEQUISISTLAN
13,MÉXICO,OAXACA,MAGDALENA TLACOTEPEC
10,MÉXICO,OAXACA,MARISCALA DE JUAREZ
19,MÉXICO,OAXACA,MARTIRES DE TACUBAYA
525,MÉXICO,OAXACA,MATIAS ROMERO AVENDAÑO
243,MÉXICO,OAXACA,MAZATLAN VILLA DE FLORES
5035,MÉXICO,OAXACA,MIAHUATLAN DE PORFIRIO DIAZ
3,MÉXICO,OAXACA,MIXISTLAN DE LA REFORMA
106,MÉXICO,OAXACA,MONJAS
13,MÉXICO,OAXACA,NATIVIDAD
321,MÉXICO,OAXACA,NAZARENO ETLA
14,MÉXICO,OAXACA,NEJAPA DE MADERO
70,MÉXICO,OAXACA,SANTIAGO NILTEPEC
17403,MÉXICO,OAXACA,OAXACA DE JUAREZ
2094,MÉXICO,OAXACA,OCOTLAN DE MORELOS
28,MÉXICO,OAXACA,LA PE
270,MÉXICO,OAXACA,PINOTEPA DE DON LUIS
51,MÉXICO,OAXACA,PLUMA HIDALGO
482,MÉXICO,OAXACA,SAN JOSE DEL PROGRESO
509,MÉXICO,OAXACA,PUTLA VILLA DE GUERRERO
26,MÉXICO,OAXACA,SANTA CATARINA QUIOQUITANI
77,MÉXICO,OAXACA,REFORMA DE PINEDA
10,MÉXICO,OAXACA,LA REFORMA
760,MÉXICO,OAXACA,REYES ETLA
57,MÉXICO,OAXACA,ROJAS DE CUAUHTEMOC
908,MÉXICO,OAXACA,SALINA CRUZ
23,MÉXICO,OAXACA,SAN AGUSTIN AMATENGO
5,MÉXICO,OAXACA,SAN AGUSTIN ATENANGO
61,MÉXICO,OAXACA,SAN AGUSTIN CHAYUCO
613,MÉXICO,OAXACA,SAN AGUSTIN DE LAS JUNTAS
937,MÉXICO,OAXACA,SAN AGUSTIN ETLA
166,MÉXICO,OAXACA,SAN AGUSTIN LOXICHA
5,MÉXICO,OAXACA,SAN AGUSTIN TLACOTEPEC
177,MÉXICO,OAXACA,SAN AGUSTIN YATARENI
10,MÉXICO,OAXACA,SAN ANDRES CABECERA NUEVA
7,MÉXICO,OAXACA,SAN ANDRES DINICUITI
248,MÉXICO,OAXACA,SAN ANDRES HUAXPALTEPEC
417,MÉXICO,OAXACA,SAN ANDRES HUAYAPAM
34,MÉXICO,OAXACA,SAN ANDRES IXTLAHUACA
2,MÉXICO,OAXACA,SAN ANDRES NUXIÑO
109,MÉXICO,OAXACA,SAN ANDRES PAXTLAN
8,MÉXICO,OAXACA,SAN ANDRES SINAXTLA
3,MÉXICO,OAXACA,SAN ANDRES SOLAGA
30,MÉXICO,OAXACA,SAN ANDRES TEOTILALPAM
6,MÉXICO,OAXACA,SAN ANDRES ZABACHE
530,MÉXICO,OAXACA,SAN ANDRES ZAUTLA
403,MÉXICO,OAXACA,SAN ANTONINO CASTILLO VELASCO
29,MÉXICO,OAXACA,SAN ANTONINO EL ALTO
21,MÉXICO,OAXACA,SAN ANTONINO MONTE VERDE
1395,MÉXICO,OAXACA,SAN ANTONIO DE LA CAL
14,MÉXICO,OAXACA,SAN ANTONIO HUITEPEC
19,MÉXICO,OAXACA,SAN ANTONIO NANAHUATIPAM
5,MÉXICO,OAXACA,SAN ANTONIO SINICAHUA
131,MÉXICO,OAXACA,SAN ANTONIO TEPETLAPA
101,MÉXICO,OAXACA,SAN BALTAZAR CHICHICAPAM
6,MÉXICO,OAXACA,SAN BALTAZAR LOXICHA
4,MÉXICO,OAXACA,SAN BALTAZAR YATZACHI EL BAJO
893,MÉXICO,OAXACA,SAN BARTOLO COYOTEPEC
358,MÉXICO,OAXACA,SAN BARTOLOME AYAUTLA
8,MÉXICO,OAXACA,SAN BARTOLOME LOXICHA
49,MÉXICO,OAXACA,SAN BARTOLOME QUIALANA
1,MÉXICO,OAXACA,SAN BARTOLOME YUCUAÑE
138,MÉXICO,OAXACA,SAN BERNARDO MIXTEPEC
102,MÉXICO,OAXACA,SAN BLAS ATEMPA
13,MÉXICO,OAXACA,SAN CARLOS YAUTEPEC
259,MÉXICO,OAXACA,SAN CRISTOBAL AMATLAN
7,MÉXICO,OAXACA,SAN CRISTOBAL AMOLTEPEC
120,MÉXICO,OAXACA,SAN DIONISIO DEL MAR
291,MÉXICO,OAXACA,SAN DIONISIO OCOTEPEC
154,MÉXICO,OAXACA,SAN DIONISIO OCOTLAN
40,MÉXICO,OAXACA,SAN ESTEBAN ATATLAHUCA
251,MÉXICO,OAXACA,SAN FELIPE JALAPA DE DIAZ
733,MÉXICO,OAXACA,SAN FELIPE TEJALAPAM
69,MÉXICO,OAXACA,SAN FELIPE USILA
2,MÉXICO,OAXACA,SAN FRANCISCO CAHUACUA
7,MÉXICO,OAXACA,SAN FRANCISCO CAJONOS
1,MÉXICO,OAXACA,SAN FRANCISCO CHAPULAPA
83,MÉXICO,OAXACA,SAN FRANCISCO DEL MAR
12,MÉXICO,OAXACA,SAN FRANCISCO HUEHUETLAN
55,MÉXICO,OAXACA,SAN FRANCISCO IXHUATAN
207,MÉXICO,OAXACA,SAN FRANCISCO LACHIGOLO
10,MÉXICO,OAXACA,SAN FRANCISCO LOGUECHE
19,MÉXICO,OAXACA,SAN FRANCISCO OZOLOTEPEC
43,MÉXICO,OAXACA,SAN FRANCISCO SOLA
455,MÉXICO,OAXACA,SAN FRANCISCO TELIXTLAHUACA
3,MÉXICO,OAXACA,SAN FRANCISCO TLAPANCINGO
35,MÉXICO,OAXACA,SAN GABRIEL MIXTEPEC
49,MÉXICO,OAXACA,SAN ILDEFONSO AMATLAN
15,MÉXICO,OAXACA,SAN ILDEFONSO SOLA
28,MÉXICO,OAXACA,SAN ILDEFONSO VILLA ALTA
925,MÉXICO,OAXACA,SAN JACINTO AMILPAS
4,MÉXICO,OAXACA,SAN JACINTO TLACOTEPEC
30,MÉXICO,OAXACA,SAN JERONIMO COATLAN
31,MÉXICO,OAXACA,SAN JERONIMO SILACAYOAPILLA
6,MÉXICO,OAXACA,SAN JERONIMO SOSOLA
70,MÉXICO,OAXACA,SAN JERONIMO TAVICHE
104,MÉXICO,OAXACA,SAN JERONIMO TECOATL
3,MÉXICO,OAXACA,SAN JORGE NUCHITA
3,MÉXICO,OAXACA,SAN JOSE AYUQUILA
460,MÉXICO,OAXACA,SAN JOSE CHILTEPEC
77,MÉXICO,OAXACA,SAN JOSE DEL PEÑASCO
37,MÉXICO,OAXACA,SAN JOSE ESTANCIA GRANDE
7,MÉXICO,OAXACA,SAN JOSE INDEPENDENCIA
24,MÉXICO,OAXACA,SAN JOSE LACHIGUIRI
645,MÉXICO,OAXACA,SAN JOSE TENANGO
1,MÉXICO,OAXACA,SAN JUAN ACHIUTLA
9,MÉXICO,OAXACA,SAN JUAN ATEPEC
337,MÉXICO,OAXACA,ANIMAS TRUJANO
13,MÉXICO,OAXACA,SAN JUAN BAUTISTA ATATLAHUCA
6,MÉXICO,OAXACA,SAN JUAN BAUTISTA COIXTLAHUACA
79,MÉXICO,OAXACA,SAN JUAN BAUTISTA CUICATLAN
1321,MÉXICO,OAXACA,SAN JUAN BAUTISTA GUELACHE
56,MÉXICO,OAXACA,SAN JUAN BAUTISTA JAYACATLAN
44,MÉXICO,OAXACA,SAN JUAN BAUTISTA LO DE SOTO
15,MÉXICO,OAXACA,SAN JUAN BAUTISTA SUCHITEPEC
1,MÉXICO,OAXACA,SAN JUAN BAUTISTA TLACHICHILCO
4752,MÉXICO,OAXACA,SAN JUAN BAUTISTA TUXTEPEC
119,MÉXICO,OAXACA,SAN JUAN CACAHUATEPEC
1,MÉXICO,OAXACA,SAN JUAN CIENEGUILLA
82,MÉXICO,OAXACA,SAN JUAN COATZOSPAM
161,MÉXICO,OAXACA,SAN JUAN COLORADO
1,MÉXICO,OAXACA,SAN JUAN COMALTEPEC
107,MÉXICO,OAXACA,SAN JUAN COTZOCON
4,MÉXICO,OAXACA,SAN JUAN CHICOMEZUCHIL
183,MÉXICO,OAXACA,SAN JUAN CHILATECA
343,MÉXICO,OAXACA,SAN JUAN DEL ESTADO
19,MÉXICO,OAXACA,SAN JUAN DEL RIO
2,MÉXICO,OAXACA,SAN JUAN EVANGELISTA ANALCO
204,MÉXICO,OAXACA,SAN JUAN GUELAVIA
450,MÉXICO,OAXACA,SAN JUAN GUICHICOVI
29,MÉXICO,OAXACA,SAN JUAN JUQUILA MIXES
2,MÉXICO,OAXACA,SAN JUAN JUQUILA VIJANOS
24,MÉXICO,OAXACA,SAN JUAN LACHAO
17,MÉXICO,OAXACA,SAN JUAN LACHIGALLA
1,MÉXICO,OAXACA,SAN JUAN LAJARCIA
11,MÉXICO,OAXACA,SAN JUAN LALANA
18,MÉXICO,OAXACA,SAN JUAN DE LOS CUES
33,MÉXICO,OAXACA,SAN JUAN MAZATLAN
36,MÉXICO,OAXACA,SAN JUAN MIXTEPEC -DTO. 08 -
5,MÉXICO,OAXACA,SAN JUAN MIXTEPEC -DTO. 26 -
21,MÉXICO,OAXACA,SAN JUAN ÑUMI
34,MÉXICO,OAXACA,SAN JUAN OZOLOTEPEC
4,MÉXICO,OAXACA,SAN JUAN PETLAPA
4,MÉXICO,OAXACA,SAN JUAN QUIAHIJE
3,MÉXICO,OAXACA,SAN JUAN QUIOTEPEC
7,MÉXICO,OAXACA,SAN JUAN SAYULTEPEC
3,MÉXICO,OAXACA,SAN JUAN TABAA
2,MÉXICO,OAXACA,SAN JUAN TAMAZOLA
1,MÉXICO,OAXACA,SAN JUAN TEITA
20,MÉXICO,OAXACA,SAN JUAN TEITIPAC
9,MÉXICO,OAXACA,SAN JUAN TEPOSCOLULA
1,MÉXICO,OAXACA,SAN JUAN YATZONA
2,MÉXICO,OAXACA,SAN JUAN YUCUITA
104,MÉXICO,OAXACA,SAN LORENZO
43,MÉXICO,OAXACA,SAN LORENZO ALBARRADAS
1254,MÉXICO,OAXACA,SAN LORENZO CACAOTEPEC
24,MÉXICO,OAXACA,SAN LORENZO CUAUNECUILTITLA
26,MÉXICO,OAXACA,SAN LORENZO TEXMELUCAN
5,MÉXICO,OAXACA,SAN LORENZO VICTORIA
6,MÉXICO,OAXACA,SAN LUCAS CAMOTLAN
190,MÉXICO,OAXACA,SAN LUCAS OJITLAN
60,MÉXICO,OAXACA,SAN LUCAS QUIAVINI
108,MÉXICO,OAXACA,SAN LUCAS ZOQUIAPAM
56,MÉXICO,OAXACA,SAN LUIS AMATLAN
36,MÉXICO,OAXACA,SAN MARCIAL OZOLOTEPEC
17,MÉXICO,OAXACA,SAN MARCOS ARTEAGA
19,MÉXICO,OAXACA,SAN MARTIN DE LOS CANSECOS
17,MÉXICO,OAXACA,SAN MARTIN HUAMELULPAM
11,MÉXICO,OAXACA,SAN MARTIN ITUNYOSO
39,MÉXICO,OAXACA,SAN MARTIN LACHILA
91,MÉXICO,OAXACA,SAN MARTIN TILCAJETE
31,MÉXICO,OAXACA,SAN MARTIN TOXPALAN
7,MÉXICO,OAXACA,SAN MATEO CAJONOS
7,MÉXICO,OAXACA,CAPULALPAM DE MENDEZ
5,MÉXICO,OAXACA,SAN MATEO DEL MAR
347,MÉXICO,OAXACA,SAN MATEO YOLOXOCHITLAN
5,MÉXICO,OAXACA,SAN MATEO ETLATONGO
15,MÉXICO,OAXACA,SAN MATEO PEÑASCO
9,MÉXICO,OAXACA,SAN MATEO PIÑAS
96,MÉXICO,OAXACA,SAN MATEO RIO HONDO
5,MÉXICO,OAXACA,SAN MATEO SINDIHUI
1,MÉXICO,OAXACA,SAN MATEO TLAPILTEPEC
4,MÉXICO,OAXACA,SAN MELCHOR BETAZA
22,MÉXICO,OAXACA,SAN MIGUEL ACHIUTLA
197,MÉXICO,OAXACA,SAN MIGUEL ALOAPAM
8,MÉXICO,OAXACA,SAN MIGUEL AMATITLAN
27,MÉXICO,OAXACA,SAN MIGUEL AMATLAN
61,MÉXICO,OAXACA,SAN MIGUEL COATLAN
4,MÉXICO,OAXACA,SAN MIGUEL CHICAHUA
24,MÉXICO,OAXACA,SAN MIGUEL CHIMALAPA
187,MÉXICO,OAXACA,SAN MIGUEL DEL PUERTO
8,MÉXICO,OAXACA,SAN MIGUEL DEL RIO
22,MÉXICO,OAXACA,SAN MIGUEL EJUTLA
20,MÉXICO,OAXACA,SAN MIGUEL EL GRANDE
3,MÉXICO,OAXACA,SAN MIGUEL HUAUTLA
122,MÉXICO,OAXACA,SAN MIGUEL MIXTEPEC
8,MÉXICO,OAXACA,SAN MIGUEL PANIXTLAHUACA
33,MÉXICO,OAXACA,SAN MIGUEL PERAS
6,MÉXICO,OAXACA,SAN MIGUEL QUETZALTEPEC MIXE
106,MÉXICO,OAXACA,VILLA SOLA DE VEGA
659,MÉXICO,OAXACA,SAN MIGUEL SOYALTEPEC
31,MÉXICO,OAXACA,SAN MIGUEL SUCHIXTEPEC
8,MÉXICO,OAXACA,VILLA TALEA DE CASTRO
3,MÉXICO,OAXACA,SAN MIGUEL TENANGO
1,MÉXICO,OAXACA,SAN MIGUEL TEQUIXTEPEC
56,MÉXICO,OAXACA,SAN MIGUEL TILQUIAPAM
129,MÉXICO,OAXACA,SAN MIGUEL TLACAMAMA
17,MÉXICO,OAXACA,SAN MIGUEL TLACOTEPEC
1,MÉXICO,OAXACA,SAN MIGUEL YOTAO
71,MÉXICO,OAXACA,SAN NICOLAS
1,MÉXICO,OAXACA,SAN NICOLAS HIDALGO
64,MÉXICO,OAXACA,SAN PABLO COATLAN
4,MÉXICO,OAXACA,SAN PABLO CUATRO VENADOS
1434,MÉXICO,OAXACA,SAN PABLO ETLA
376,MÉXICO,OAXACA,SAN PABLO HUITZO
585,MÉXICO,OAXACA,SAN PABLO HUIXTEPEC
1,MÉXICO,OAXACA,SAN PABLO MACUILTIANGUIS
87,MÉXICO,OAXACA,SAN PABLO TIJALTEPEC
689,MÉXICO,OAXACA,SAN PABLO VILLA DE MITLA
7,MÉXICO,OAXACA,SAN PABLO YAGANIZA
153,MÉXICO,OAXACA,SAN PEDRO AMUZGOS
38,MÉXICO,OAXACA,SAN PEDRO APOSTOL
115,MÉXICO,OAXACA,SAN PEDRO ATOYAC
39,MÉXICO,OAXACA,SAN PEDRO CAJONOS
52,MÉXICO,OAXACA,SAN PEDRO COMITANCILLO
49,MÉXICO,OAXACA,SAN PEDRO EL ALTO
232,MÉXICO,OAXACA,SAN PEDRO HUAMELULA
34,MÉXICO,OAXACA,SAN PEDRO HUILOTEPEC
44,MÉXICO,OAXACA,SAN PEDRO IXCATLAN
539,MÉXICO,OAXACA,SAN PEDRO IXTLAHUACA
323,MÉXICO,OAXACA,SAN PEDRO JICAYAN
7,MÉXICO,OAXACA,SAN PEDRO JUCHATENGO
111,MÉXICO,OAXACA,SAN PEDRO MARTIR
1,MÉXICO,OAXACA,SAN PEDRO MARTIR QUIECHAPA
19,MÉXICO,OAXACA,SAN PEDRO MARTIR YUCUXACO
1829,MÉXICO,OAXACA,SAN PEDRO MIXTEPEC -DTO. 22 -
2,MÉXICO,OAXACA,SAN PEDRO MIXTEPEC -DTO. 26 -
57,MÉXICO,OAXACA,SAN PEDRO MOLINOS
100,MÉXICO,OAXACA,SAN PEDRO OCOPETATILLO
3977,MÉXICO,OAXACA,SAN PEDRO POCHUTLA
56,MÉXICO,OAXACA,SAN PEDRO QUIATONI
779,MÉXICO,OAXACA,SAN PEDRO TAPANATEPEC
86,MÉXICO,OAXACA,SAN PEDRO TAVICHE
4,MÉXICO,OAXACA,SAN PEDRO TEOZACOALCO
1,MÉXICO,OAXACA,SAN PEDRO TEUTILA
58,MÉXICO,OAXACA,SAN PEDRO TOTOLAPAM
992,MÉXICO,OAXACA,VILLA DE TUTUTEPEC DE MELCHOR OCAMPO
1,MÉXICO,OAXACA,SAN PEDRO YANERI
14,MÉXICO,OAXACA,SAN PEDRO YOLOX
176,MÉXICO,OAXACA,SAN PEDRO Y SAN PABLO AYUTLA
2504,MÉXICO,OAXACA,VILLA DE ETLA
75,MÉXICO,OAXACA,SAN PEDRO Y SAN PABLO TEPOSCOLULA
6,MÉXICO,OAXACA,SAN PEDRO Y SAN PABLO TEQUIXTEPEC
1,MÉXICO,OAXACA,SAN PEDRO YUCUNAMA
337,MÉXICO,OAXACA,SAN RAYMUNDO JALPAN
68,MÉXICO,OAXACA,SAN SEBASTIAN ABASOLO
22,MÉXICO,OAXACA,SAN SEBASTIAN COATLAN
82,MÉXICO,OAXACA,SAN SEBASTIAN IXCAPA
139,MÉXICO,OAXACA,SAN SEBASTIAN RIO HONDO
40,MÉXICO,OAXACA,SAN SEBASTIAN TECOMAXTLAHUACA
68,MÉXICO,OAXACA,SAN SEBASTIAN TEITIPAC
1119,MÉXICO,OAXACA,SAN SEBASTIAN TUTLA
103,MÉXICO,OAXACA,SAN SIMON ALMOLONGAS
70,MÉXICO,OAXACA,SANTA ANA
10,MÉXICO,OAXACA,SANTA ANA ATEIXTLAHUACA
177,MÉXICO,OAXACA,SANTA ANA DEL VALLE
2,MÉXICO,OAXACA,SANTA ANA TAVELA
72,MÉXICO,OAXACA,SANTA ANA TLAPACOYAN
2,MÉXICO,OAXACA,SANTA ANA YARENI
267,MÉXICO,OAXACA,SANTA ANA ZEGACHE
17,MÉXICO,OAXACA,SANTA CATALINA QUIERI
106,MÉXICO,OAXACA,SANTA CATARINA CUIXTLA
60,MÉXICO,OAXACA,SANTA CATARINA IXTEPEJI
340,MÉXICO,OAXACA,SANTA CATARINA JUQUILA
4,MÉXICO,OAXACA,SANTA CATARINA LACHATAO
26,MÉXICO,OAXACA,SANTA CATARINA LOXICHA
117,MÉXICO,OAXACA,SANTA CATARINA MECHOACAN
139,MÉXICO,OAXACA,SANTA CATARINA MINAS
360,MÉXICO,OAXACA,SANTA CATARINA QUIANE
8,MÉXICO,OAXACA,SANTA CATARINA TAYATA
386,MÉXICO,OAXACA,SANTA CATARINA TICUA
4,MÉXICO,OAXACA,SANTA CATARINA YOSONOTU
50,MÉXICO,OAXACA,SANTA CRUZ ACATEPEC
720,MÉXICO,OAXACA,SANTA CRUZ AMILPAS
26,MÉXICO,OAXACA,SANTA CRUZ ITUNDUJIA
278,MÉXICO,OAXACA,SANTA CRUZ MIXTEPEC
8,MÉXICO,OAXACA,SANTA CRUZ NUNDACO
34,MÉXICO,OAXACA,SANTA CRUZ PAPALUTLA
4,MÉXICO,OAXACA,SANTA CRUZ TACACHE DE MINA
6,MÉXICO,OAXACA,SANTA CRUZ TAYATA
405,MÉXICO,OAXACA,SANTA CRUZ XITLA
7304,MÉXICO,OAXACA,SANTA CRUZ XOXOCOTLAN
22,MÉXICO,OAXACA,SANTA CRUZ ZENZONTEPEC
224,MÉXICO,OAXACA,SANTA GERTRUDIS
162,MÉXICO,OAXACA,SANTA INES DEL MONTE
6,MÉXICO,OAXACA,SANTA INES YATZECHE
2561,MÉXICO,OAXACA,SANTA LUCIA DEL CAMINO
126,MÉXICO,OAXACA,SANTA LUCIA MIAHUATLAN
3,MÉXICO,OAXACA,SANTA LUCIA MONTEVERDE
152,MÉXICO,OAXACA,SANTA LUCIA OCOTLAN
13,MÉXICO,OAXACA,SANTA MARIA ALOTEPEC
4,MÉXICO,OAXACA,SANTA MARIA APAZCO
144,MÉXICO,OAXACA,SANTA MARIA LA ASUNCION
2142,MÉXICO,OAXACA,HEROICA CIUDAD DE TLAXIACO
260,MÉXICO,OAXACA,AYOQUEZCO DE ALDAMA
1879,MÉXICO,OAXACA,SANTA MARIA ATZOMPA
2,MÉXICO,OAXACA,SANTA MARIA CAMOTLAN
672,MÉXICO,OAXACA,SANTA MARIA COLOTEPEC
53,MÉXICO,OAXACA,SANTA MARIA CORTIJO
170,MÉXICO,OAXACA,SANTA MARIA COYOTEPEC
4,MÉXICO,OAXACA,SANTA MARIA CHACHOAPAM
2,MÉXICO,OAXACA,VILLA DE CHILAPA DE DIAZ
619,MÉXICO,OAXACA,SANTA MARIA CHILCHOTLA
34,MÉXICO,OAXACA,SANTA MARIA CHIMALAPA
7,MÉXICO,OAXACA,SANTA MARIA DEL ROSARIO
710,MÉXICO,OAXACA,SANTA MARIA DEL TULE
1,MÉXICO,OAXACA,SANTA MARIA ECATEPEC
22,MÉXICO,OAXACA,SANTA MARIA GUELACE
8,MÉXICO,OAXACA,SANTA MARIA GUIENAGATI
3226,MÉXICO,OAXACA,SANTA MARIA HUATULCO
398,MÉXICO,OAXACA,SANTA MARIA HUAZOLOTITLAN
20,MÉXICO,OAXACA,SANTA MARIA IPALAPA
442,MÉXICO,OAXACA,SANTA MARIA JACATEPEC
174,MÉXICO,OAXACA,SANTA MARIA JALAPA DEL MARQUES
2,MÉXICO,OAXACA,SANTA MARIA JALTIANGUIS
7,MÉXICO,OAXACA,SANTA MARIA LACHIXIO
18,MÉXICO,OAXACA,SANTA MARIA MIXTEQUILLA
1,MÉXICO,OAXACA,SANTA MARIA NATIVITAS
2,MÉXICO,OAXACA,SANTA MARIA NDUAYACO
49,MÉXICO,OAXACA,SANTA MARIA OZOLOTEPEC
23,MÉXICO,OAXACA,SANTA MARIA PEÑOLES
180,MÉXICO,OAXACA,SANTA MARIA PETAPA
2,MÉXICO,OAXACA,SANTA MARIA QUIEGOLANI
3,MÉXICO,OAXACA,SANTA MARIA SOLA
1,MÉXICO,OAXACA,SANTA MARIA TATALTEPEC
18,MÉXICO,OAXACA,SANTA MARIA TECOMAVACA
1,MÉXICO,OAXACA,SANTA MARIA TEMAXCALAPA
4,MÉXICO,OAXACA,SANTA MARIA TEMAXCALTEPEC
56,MÉXICO,OAXACA,SANTA MARIA TEOPOXCO
12,MÉXICO,OAXACA,SANTA MARIA TEPANTLALI
4,MÉXICO,OAXACA,SANTA MARIA TEXCATITLAN
45,MÉXICO,OAXACA,SANTA MARIA TLAHUITOLTEPEC
1367,MÉXICO,OAXACA,SANTA MARIA TONAMECA
12,MÉXICO,OAXACA,SANTA MARIA TOTOLAPILLA
130,MÉXICO,OAXACA,SANTA MARIA XADANI
2,MÉXICO,OAXACA,SANTA MARIA YOLOTEPEC
12,MÉXICO,OAXACA,SANTA MARIA YOSOYUA
27,MÉXICO,OAXACA,SANTA MARIA YUCUHITI
50,MÉXICO,OAXACA,SANTA MARIA ZACATEPEC
1,MÉXICO,OAXACA,SANTA MARIA ZANIZA
3,MÉXICO,OAXACA,SANTA MARIA ZOQUITLAN
1,MÉXICO,OAXACA,SANTIAGO AMOLTEPEC
2,MÉXICO,OAXACA,SANTIAGO APOALA
211,MÉXICO,OAXACA,SANTIAGO APOSTOL
136,MÉXICO,OAXACA,SANTIAGO ASTATA
7,MÉXICO,OAXACA,SANTIAGO ATITLAN
17,MÉXICO,OAXACA,SANTIAGO AYUQUILILLA
29,MÉXICO,OAXACA,SANTIAGO CACALOXTEPEC
15,MÉXICO,OAXACA,SANTIAGO CAMOTLAN
12,MÉXICO,OAXACA,SANTIAGO COMALTEPEC
40,MÉXICO,OAXACA,SANTIAGO CHAZUMBA
9,MÉXICO,OAXACA,SANTIAGO CHOAPAM
69,MÉXICO,OAXACA,SANTIAGO HUAJOLOTITLAN
10,MÉXICO,OAXACA,SANTIAGO IHUITLAN PLUMAS
1,MÉXICO,OAXACA,SANTIAGO IXCUINTEPEC
44,MÉXICO,OAXACA,SANTIAGO IXTAYUTLA
485,MÉXICO,OAXACA,SANTIAGO JAMILTEPEC
22,MÉXICO,OAXACA,SANTIAGO JOCOTEPEC
262,MÉXICO,OAXACA,SANTIAGO JUXTLAHUACA
36,MÉXICO,OAXACA,SANTIAGO LAOLLAGA
92,MÉXICO,OAXACA,SANTIAGO LLANO GRANDE
478,MÉXICO,OAXACA,SANTIAGO MATATLAN
1,MÉXICO,OAXACA,SANTIAGO MILTEPEC
5,MÉXICO,OAXACA,SANTIAGO MINAS
8,MÉXICO,OAXACA,SANTIAGO NACALTEPEC
10,MÉXICO,OAXACA,SANTIAGO NUNDICHE
8,MÉXICO,OAXACA,SANTIAGO NUYOO
1883,MÉXICO,OAXACA,SANTIAGO PINOTEPA NACIONAL
1024,MÉXICO,OAXACA,SANTIAGO SUCHILQUITONGO
11,MÉXICO,OAXACA,SANTIAGO TAMAZOLA
8,MÉXICO,OAXACA,SANTIAGO TAPEXTLA
61,MÉXICO,OAXACA,VILLA TEJUPAM DE LA UNION
25,MÉXICO,OAXACA,SANTIAGO TENANGO
54,MÉXICO,OAXACA,SANTIAGO TETEPEC
1,MÉXICO,OAXACA,SANTIAGO TEXCALCINGO
9,MÉXICO,OAXACA,SANTIAGO TEXTITLAN
1,MÉXICO,OAXACA,SANTIAGO TILANTONGO
1,MÉXICO,OAXACA,SANTIAGO TILLO
13,MÉXICO,OAXACA,SANTIAGO TLAZOYALTEPEC
15,MÉXICO,OAXACA,SANTIAGO XANICA
12,MÉXICO,OAXACA,SANTIAGO XIACUI
3,MÉXICO,OAXACA,SANTIAGO YAITEPEC
28,MÉXICO,OAXACA,SANTIAGO YAVEO
43,MÉXICO,OAXACA,SANTIAGO YOLOMECATL
6,MÉXICO,OAXACA,SANTIAGO YOSONDUA
28,MÉXICO,OAXACA,SANTIAGO ZACATEPEC
35,MÉXICO,OAXACA,NUEVO ZOQUIAPAM
19,MÉXICO,OAXACA,SANTO DOMINGO INGENIO
51,MÉXICO,OAXACA,SANTO DOMINGO ALBARRADAS
53,MÉXICO,OAXACA,SANTO DOMINGO ARMENTA
21,MÉXICO,OAXACA,SANTO DOMINGO CHIHUITAN
165,MÉXICO,OAXACA,SANTO DOMINGO DE MORELOS
6,MÉXICO,OAXACA,SANTO DOMINGO NUXAA
2,MÉXICO,OAXACA,SANTO DOMINGO OZOLOTEPEC
102,MÉXICO,OAXACA,SANTO DOMINGO PETAPA
1,MÉXICO,OAXACA,SANTO DOMINGO ROAYAGA
393,MÉXICO,OAXACA,SANTO DOMINGO TEHUANTEPEC
11,MÉXICO,OAXACA,SANTO DOMINGO TEOJOMULCO
22,MÉXICO,OAXACA,SANTO DOMINGO TEPUXTEPEC
152,MÉXICO,OAXACA,SANTO DOMINGO TOMALTEPEC
12,MÉXICO,OAXACA,SANTO DOMINGO TONALA
3,MÉXICO,OAXACA,SANTO DOMINGO TONALTEPEC
1,MÉXICO,OAXACA,SANTO DOMINGO XAGACIA
6,MÉXICO,OAXACA,SANTO DOMINGO YANHUITLAN
2,MÉXICO,OAXACA,SANTO DOMINGO YODOHINO
415,MÉXICO,OAXACA,SANTO DOMINGO ZANATEPEC
68,MÉXICO,OAXACA,SANTOS REYES NOPALA
3,MÉXICO,OAXACA,SANTOS REYES PAPALO
1,MÉXICO,OAXACA,SANTOS REYES TEPEJILLO
101,MÉXICO,OAXACA,SANTO TOMAS JALIEZA
163,MÉXICO,OAXACA,SANTO TOMAS MAZALTEPEC
8,MÉXICO,OAXACA,SANTO TOMAS OCOTEPEC
217,MÉXICO,OAXACA,SANTO TOMAS TAMAZULAPAN
20,MÉXICO,OAXACA,SAN VICENTE COATLAN
13,MÉXICO,OAXACA,SAN VICENTE LACHIXIO
1,MÉXICO,OAXACA,SAN VICENTE NUÑU
29,MÉXICO,OAXACA,SILACAYOAPAM
36,MÉXICO,OAXACA,SITIO DE XITLAPEHUA
399,MÉXICO,OAXACA,SOLEDAD ETLA
19,MÉXICO,OAXACA,VILLA DE TAMAZULAPAM DEL PROGRESO
1,MÉXICO,OAXACA,TANETZE DE ZARAGOZA
9,MÉXICO,OAXACA,TANICHE
28,MÉXICO,OAXACA,TATALTEPEC DE VALDES
100,MÉXICO,OAXACA,TEOCOCUILCO DE MARCOS PEREZ
106,MÉXICO,OAXACA,TEOTITLAN DE FLORES MAGON
216,MÉXICO,OAXACA,TEOTITLAN DEL VALLE
2,MÉXICO,OAXACA,TEOTONGO
55,MÉXICO,OAXACA,TEZOATLAN DE SEGURA Y LUNA
238,MÉXICO,OAXACA,SAN JERONIMO TLACOCHAHUAYA
2407,MÉXICO,OAXACA,TLACOLULA DE MATAMOROS
1,MÉXICO,OAXACA,TLACOTEPEC PLUMAS
421,MÉXICO,OAXACA,TLALIXTAC DE CABRERA
18,MÉXICO,OAXACA,TOTONTEPEC VILLA DE MORELOS
393,MÉXICO,OAXACA,TRINIDAD ZAACHILA
3,MÉXICO,OAXACA,LA TRINIDAD VISTA HERMOSA
57,MÉXICO,OAXACA,UNION HIDALGO
4,MÉXICO,OAXACA,VALERIO TRUJANO
3302,MÉXICO,OAXACA,SAN JUAN BAUTISTA VALLE NACIONAL
213,MÉXICO,OAXACA,VILLA DIAZ ORDAZ
37,MÉXICO,OAXACA,YAXE
1,MÉXICO,OAXACA,MAGDALENA YODOCONO DE PORFIRIO DIAZ
17,MÉXICO,OAXACA,YOGANA
1,MÉXICO,OAXACA,YUTANDUCHI DE GUERRERO
5466,MÉXICO,OAXACA,VILLA DE ZAACHILA
1,MÉXICO,OAXACA,ZAPOTITLAN DEL RIO
5,MÉXICO,OAXACA,ZAPOTITLAN PALMAS
1,MÉXICO,OAXACA,SANTA INES DE ZARAGOZA
2732,MÉXICO,OAXACA,ZIMATLAN DE ALVAREZ
17,MÉXICO,PUEBLA,ACAJETE
3,MÉXICO,PUEBLA,ACATENO
17,MÉXICO,PUEBLA,ACATLAN
31,MÉXICO,PUEBLA,ACATZINGO
11,MÉXICO,PUEBLA,ACTEOPAN
2,MÉXICO,PUEBLA,AHUACATLAN
3,MÉXICO,PUEBLA,AHUAZOTEPEC
353,MÉXICO,PUEBLA,AJALPAN
11,MÉXICO,PUEBLA,ALJOJUCA
160,MÉXICO,PUEBLA,ALTEPEXI
125,MÉXICO,PUEBLA,AMOZOC
1,MÉXICO,PUEBLA,AQUIXTLA
11,MÉXICO,PUEBLA,ATEMPAN
28,MÉXICO,PUEBLA,ATEXCAL
64,MÉXICO,PUEBLA,ATLIXCO
3,MÉXICO,PUEBLA,ATOYATEMPAN
1,MÉXICO,PUEBLA,ATZALA
8,MÉXICO,PUEBLA,ATZITZIHUACAN
233,MÉXICO,PUEBLA,ATZITZINTLA
18,MÉXICO,PUEBLA,AYOTOXCO DE GUERRERO
1,MÉXICO,PUEBLA,CALPAN
36,MÉXICO,PUEBLA,CALTEPEC
1,MÉXICO,PUEBLA,COATEPEC
54,MÉXICO,PUEBLA,CORONANGO
129,MÉXICO,PUEBLA,COXCATLAN
77,MÉXICO,PUEBLA,COYOMEAPAN
14,MÉXICO,PUEBLA,COYOTEPEC
3,MÉXICO,PUEBLA,CUAPIAXTLA DE MADERO
5,MÉXICO,PUEBLA,CUAUTEMPAN
6,MÉXICO,PUEBLA,CUAUTINCHAN
144,MÉXICO,PUEBLA,CUAUTLANCINGO
2,MÉXICO,PUEBLA,CUAYUCA DE ANDRADE
18,MÉXICO,PUEBLA,CUETZALAN DEL PROGRESO
60,MÉXICO,PUEBLA,CUYOACO
116,MÉXICO,PUEBLA,CHALCHICOMULA DE SESMA
221,MÉXICO,PUEBLA,CHAPULCO
3,MÉXICO,PUEBLA,CHIAUTLA
75,MÉXICO,PUEBLA,CHIAUTZINGO
2,MÉXICO,PUEBLA,CHICHIQUILA
65,MÉXICO,PUEBLA,CHIETLA
52,MÉXICO,PUEBLA,CHIGNAHUAPAN
66,MÉXICO,PUEBLA,CHIGNAUTLA
6,MÉXICO,PUEBLA,CHILA
2,MÉXICO,PUEBLA,HONEY
2,MÉXICO,PUEBLA,CHILCHOTLA
15,MÉXICO,PUEBLA,ELOXOCHITLAN
19,MÉXICO,PUEBLA,ESPERANZA
6,MÉXICO,PUEBLA,FRANCISCO Z. MENA
19,MÉXICO,PUEBLA,GENERAL FELIPE ANGELES
1,MÉXICO,PUEBLA,GUADALUPE
22,MÉXICO,PUEBLA,GUADALUPE VICTORIA
11,MÉXICO,PUEBLA,HUAQUECHULA
1,MÉXICO,PUEBLA,HUATLATLAUCA
28,MÉXICO,PUEBLA,HUAUCHINANGO
7,MÉXICO,PUEBLA,HUEHUETLA
155,MÉXICO,PUEBLA,HUEJOTZINGO
21,MÉXICO,PUEBLA,HUEYAPAN
40,MÉXICO,PUEBLA,HUEYTAMALCO
3,MÉXICO,PUEBLA,HUEYTLALPAN
3,MÉXICO,PUEBLA,HUITZILAN DE SERDAN
3,MÉXICO,PUEBLA,HUITZILTEPEC
42,MÉXICO,PUEBLA,IXCAQUIXTLA
7,MÉXICO,PUEBLA,IXTACAMAXTITLAN
1,MÉXICO,PUEBLA,IXTEPEC
44,MÉXICO,PUEBLA,IZUCAR DE MATAMOROS
3,MÉXICO,PUEBLA,JALPAN
1,MÉXICO,PUEBLA,JOLALPAN
2,MÉXICO,PUEBLA,JONOTLA
68,MÉXICO,PUEBLA,JUAN C. BONILLA
1,MÉXICO,PUEBLA,JUAN GALINDO
4,MÉXICO,PUEBLA,JUAN N. MENDEZ
38,MÉXICO,PUEBLA,LAFRAGUA
70,MÉXICO,PUEBLA,LIBRES
26,MÉXICO,PUEBLA,MAZAPILTEPEC DE JUAREZ
2,MÉXICO,PUEBLA,MIXTLA
11,MÉXICO,PUEBLA,MOLCAXAC
96,MÉXICO,PUEBLA,CAÑADA MORELOS
2,MÉXICO,PUEBLA,NEALTICAN
32,MÉXICO,PUEBLA,NICOLAS BRAVO
27,MÉXICO,PUEBLA,NOPALUCAN
28,MÉXICO,PUEBLA,OCOTEPEC
10,MÉXICO,PUEBLA,OCOYUCAN
15,MÉXICO,PUEBLA,ORIENTAL
4,MÉXICO,PUEBLA,PAHUATLAN
240,MÉXICO,PUEBLA,PALMAR DE BRAVO
3,MÉXICO,PUEBLA,PETLALCINGO
3771,MÉXICO,PUEBLA,PUEBLA
46,MÉXICO,PUEBLA,QUECHOLAC
1,MÉXICO,PUEBLA,QUIMIXTLAN
33,MÉXICO,PUEBLA,RAFAEL LARA GRAJALES
7,MÉXICO,PUEBLA,LOS REYES DE JUAREZ
185,MÉXICO,PUEBLA,SAN ANDRES CHOLULA
71,MÉXICO,PUEBLA,SAN ANTONIO CAÑADA
5,MÉXICO,PUEBLA,SAN FELIPE TEOTLALCINGO
175,MÉXICO,PUEBLA,SAN GABRIEL CHILAC
14,MÉXICO,PUEBLA,SAN GREGORIO ATZOMPA
7,MÉXICO,PUEBLA,SAN JERONIMO TECUANIPAN
49,MÉXICO,PUEBLA,SAN JOSE CHIAPA
341,MÉXICO,PUEBLA,SAN JOSE MIAHUATLAN
8,MÉXICO,PUEBLA,SAN JUAN ATENCO
137,MÉXICO,PUEBLA,SAN MARTIN TEXMELUCAN
2,MÉXICO,PUEBLA,SAN MARTIN TOTOLTEPEC
23,MÉXICO,PUEBLA,SAN MATIAS TLALANCALECA
46,MÉXICO,PUEBLA,SAN MIGUEL XOXTLA
7,MÉXICO,PUEBLA,SAN NICOLAS BUENOS AIRES
212,MÉXICO,PUEBLA,SAN PEDRO CHOLULA
52,MÉXICO,PUEBLA,SAN SALVADOR EL SECO
12,MÉXICO,PUEBLA,SAN SALVADOR EL VERDE
25,MÉXICO,PUEBLA,SAN SALVADOR HUIXCOLOTLA
8,MÉXICO,PUEBLA,SAN SEBASTIAN TLACOTEPEC
1,MÉXICO,PUEBLA,SANTA CATARINA TLALTEMPAN
61,MÉXICO,PUEBLA,SANTA INES AHUATEMPAN
8,MÉXICO,PUEBLA,SANTA ISABEL CHOLULA
252,MÉXICO,PUEBLA,SANTIAGO MIAHUATLAN
4,MÉXICO,PUEBLA,HUEHUETLAN EL GRANDE
3,MÉXICO,PUEBLA,SANTO TOMAS HUEYOTLIPAN
4,MÉXICO,PUEBLA,SOLTEPEC
56,MÉXICO,PUEBLA,TECALI DE HERRERA
394,MÉXICO,PUEBLA,TECAMACHALCO
1,MÉXICO,PUEBLA,TECOMATLAN
3948,MÉXICO,PUEBLA,TEHUACAN
1,MÉXICO,PUEBLA,TEHUITZINGO
9,MÉXICO,PUEBLA,TENAMPULCO
2,MÉXICO,PUEBLA,TEOPANTLAN
2,MÉXICO,PUEBLA,TEOTLALCO
569,MÉXICO,PUEBLA,TEPANCO DE LOPEZ
3,MÉXICO,PUEBLA,TEPATLAXCO DE HIDALGO
24,MÉXICO,PUEBLA,TEPEACA
1,MÉXICO,PUEBLA,TEPEOJUMA
7,MÉXICO,PUEBLA,TEPEXCO
144,MÉXICO,PUEBLA,TEPEXI DE RODRIGUEZ
75,MÉXICO,PUEBLA,TEPEYAHUALCO
4,MÉXICO,PUEBLA,TEPEYAHUALCO DE CUAUHTEMOC
45,MÉXICO,PUEBLA,TETELA DE OCAMPO
1,MÉXICO,PUEBLA,TETELES DE AVILA CASTILLO
297,MÉXICO,PUEBLA,TEZIUTLAN
17,MÉXICO,PUEBLA,TIANGUISMANALCO
1,MÉXICO,PUEBLA,TILAPA
1165,MÉXICO,PUEBLA,TLACOTEPEC DE BENITO JUAREZ
3,MÉXICO,PUEBLA,TLACUILOTEPEC
27,MÉXICO,PUEBLA,TLACHICHUCA
15,MÉXICO,PUEBLA,TLAHUAPAN
34,MÉXICO,PUEBLA,TLALTENANGO
8,MÉXICO,PUEBLA,TLANEPANTLA
32,MÉXICO,PUEBLA,TLATLAUQUITEPEC
1,MÉXICO,PUEBLA,TOCHIMILCO
45,MÉXICO,PUEBLA,TOCHTEPEC
3,MÉXICO,PUEBLA,TULCINGO
2,MÉXICO,PUEBLA,TUZAMAPAN DE GALEANA
4,MÉXICO,PUEBLA,TZICATLACOYAN
3,MÉXICO,PUEBLA,VENUSTIANO CARRANZA
560,MÉXICO,PUEBLA,VICENTE GUERRERO
13,MÉXICO,PUEBLA,XICOTEPEC
2,MÉXICO,PUEBLA,XICOTLAN
32,MÉXICO,PUEBLA,XIUTETELCO
3,MÉXICO,PUEBLA,XOCHIAPULCO
4,MÉXICO,PUEBLA,XOCHILTEPEC
1,MÉXICO,PUEBLA,XOCHITLAN DE VICENTE SUAREZ
20,MÉXICO,PUEBLA,XOCHITLAN TODOS SANTOS
5,MÉXICO,PUEBLA,YAONAHUAC
122,MÉXICO,PUEBLA,YEHUALTEPEC
25,MÉXICO,PUEBLA,ZACAPOAXTLA
9,MÉXICO,PUEBLA,ZACATLAN
189,MÉXICO,PUEBLA,ZAPOTITLAN
51,MÉXICO,PUEBLA,ZARAGOZA
15,MÉXICO,PUEBLA,ZAUTLA
4,MÉXICO,PUEBLA,ZIHUATEUTLA
193,MÉXICO,PUEBLA,ZINACATEPEC
55,MÉXICO,PUEBLA,ZOQUITLAN
4,MÉXICO,QUERÉTARO,CORREGIDORA
1,MÉXICO,QUERÉTARO,EL MARQUES
3,MÉXICO,QUERÉTARO,QUERETARO
2,MÉXICO,QUERÉTARO,SAN JUAN DEL RIO
18,MÉXICO,QUINTANA ROO,COZUMEL
326,MÉXICO,QUINTANA ROO,FELIPE CARRILLO PUERTO
3,MÉXICO,QUINTANA ROO,ISLA MUJERES
1191,MÉXICO,QUINTANA ROO,OTHON P. BLANCO
3224,MÉXICO,QUINTANA ROO,BENITO JUAREZ
55,MÉXICO,QUINTANA ROO,JOSE MARIA MORELOS
2549,MÉXICO,QUINTANA ROO,LAZARO CARDENAS
700,MÉXICO,QUINTANA ROO,SOLIDARIDAD
275,MÉXICO,QUINTANA ROO,TULUM
187,MÉXICO,QUINTANA ROO,BACALAR
46,MÉXICO,QUINTANA ROO,PUERTO MORELOS
1,MÉXICO,SAN LUIS POTOSÍ,SAN LUIS POTOSI
1,MÉXICO,SINALOA,MAZATLAN
1,MÉXICO,SINALOA,SINALOA
8,MÉXICO,TABASCO,CARDENAS
7,MÉXICO,TABASCO,CENTLA
24,MÉXICO,TABASCO,CENTRO
1,MÉXICO,TABASCO,EMILIANO ZAPATA
1,MÉXICO,TABASCO,JALAPA
2,MÉXICO,TABASCO,JALPA DE MENDEZ
3,MÉXICO,TABASCO,MACUSPANA
4,MÉXICO,TABASCO,NACAJUCA
1,MÉXICO,TABASCO,PARAISO
3,MÉXICO,TABASCO,TENOSIQUE
4,MÉXICO,TLAXCALA,APETATITLAN DE ANTONIO CARVAJAL
6,MÉXICO,TLAXCALA,ATLANGATEPEC
4,MÉXICO,TLAXCALA,ALTZAYANCA
3,MÉXICO,TLAXCALA,APIZACO
6,MÉXICO,TLAXCALA,CALPULALPAN
7,MÉXICO,TLAXCALA,EL CARMEN TEQUEXQUITLA
8,MÉXICO,TLAXCALA,CUAPIAXTLA
1,MÉXICO,TLAXCALA,CUAXOMULCO
4,MÉXICO,TLAXCALA,CHIAUTEMPAN
43,MÉXICO,TLAXCALA,MUÑOZ DE DOMINGO ARENAS
3,MÉXICO,TLAXCALA,ESPAÑITA
7,MÉXICO,TLAXCALA,HUAMANTLA
7,MÉXICO,TLAXCALA,HUEYOTLIPAN
14,MÉXICO,TLAXCALA,IXTACUIXTLA DE MARIANO MATAMOROS
2,MÉXICO,TLAXCALA,MAZATECOCHCO DE JOSE MARIA MORELOS
2,MÉXICO,TLAXCALA,CONTLA DE JUAN CUAMATZI
29,MÉXICO,TLAXCALA,TEPETITLA DE LARDIZABAL
3,MÉXICO,TLAXCALA,SANCTORUM DE LAZARO CARDENAS
10,MÉXICO,TLAXCALA,NANACAMILPA DE MARIANO ARISTA
12,MÉXICO,TLAXCALA,NATIVITAS
2,MÉXICO,TLAXCALA,PANOTLA
59,MÉXICO,TLAXCALA,SAN PABLO DEL MONTE
1,MÉXICO,TLAXCALA,SANTA CRUZ TLAXCALA
4,MÉXICO,TLAXCALA,TENANCINGO
4,MÉXICO,TLAXCALA,TEOLOCHOLCO
1,MÉXICO,TLAXCALA,TERRENATE
7,MÉXICO,TLAXCALA,TETLA DE LA SOLIDARIDAD
2,MÉXICO,TLAXCALA,TETLATLAHUCA
14,MÉXICO,TLAXCALA,TLAXCALA
32,MÉXICO,TLAXCALA,TLAXCO
2,MÉXICO,TLAXCALA,TOTOLAC
3,MÉXICO,TLAXCALA,ZITLALTEPEC DE TRINIDAD SANCHEZ SANTOS
3,MÉXICO,TLAXCALA,XALOZTOC
3,MÉXICO,TLAXCALA,XALTOCAN
7,MÉXICO,TLAXCALA,PAPALOTLA DE XICOHTENCATL
6,MÉXICO,TLAXCALA,XICOHTZINCO
2,MÉXICO,TLAXCALA,YAUHQUEMECAN
11,MÉXICO,TLAXCALA,ZACATELCO
1,MÉXICO,TLAXCALA,BENITO JUAREZ
2,MÉXICO,TLAXCALA,LAZARO CARDENAS
1,MÉXICO,TLAXCALA,LA MAGDALENA TLALTELULCO
7,MÉXICO,TLAXCALA,SAN DAMIAN TEXOLOC
1,MÉXICO,TLAXCALA,SAN FRANCISCO TETLANOHCAN
8,MÉXICO,TLAXCALA,SAN JOSE TEACALCO
2,MÉXICO,TLAXCALA,SAN LORENZO AXOCOMANITLA
3,MÉXICO,TLAXCALA,SAN LUCAS TECOPILCO
2,MÉXICO,TLAXCALA,SANTA APOLONIA TEACALCO
4,MÉXICO,VERACRUZ,ACAJETE
2,MÉXICO,VERACRUZ,ACAYUCAN
158,MÉXICO,VERACRUZ,ACTOPAN
4,MÉXICO,VERACRUZ,ACULA
43,MÉXICO,VERACRUZ,ACULTZINGO
7,MÉXICO,VERACRUZ,CAMARON DE TEJEDA
33,MÉXICO,VERACRUZ,ALTO LUCERO DE GUTIERREZ BARRIOS
6,MÉXICO,VERACRUZ,ALTOTONGA
95,MÉXICO,VERACRUZ,ALVARADO
21,MÉXICO,VERACRUZ,AMATITLAN
1,MÉXICO,VERACRUZ,AMATLAN DE LOS REYES
1,MÉXICO,VERACRUZ,ANGEL R. CABADA
191,MÉXICO,VERACRUZ,LA ANTIGUA
1,MÉXICO,VERACRUZ,APAZAPAN
1,MÉXICO,VERACRUZ,AQUILA
2,MÉXICO,VERACRUZ,ASTACINGA
11,MÉXICO,VERACRUZ,ATLAHUILCO
2,MÉXICO,VERACRUZ,ATOYAC
169,MÉXICO,VERACRUZ,ATZACAN
4,MÉXICO,VERACRUZ,ATZALAN
3,MÉXICO,VERACRUZ,TLALTETELA
10,MÉXICO,VERACRUZ,AYAHUALULCO
16,MÉXICO,VERACRUZ,BANDERILLA
457,MÉXICO,VERACRUZ,BOCA DEL RIO
93,MÉXICO,VERACRUZ,CAMERINO Z. MENDOZA
2,MÉXICO,VERACRUZ,CARRILLO PUERTO
3,MÉXICO,VERACRUZ,CATEMACO
171,MÉXICO,VERACRUZ,COATEPEC
5,MÉXICO,VERACRUZ,COATZACOALCOS
5,MÉXICO,VERACRUZ,COMAPA
56,MÉXICO,VERACRUZ,CORDOBA
659,MÉXICO,VERACRUZ,COSAMALOAPAN DE CARPIO
13,MÉXICO,VERACRUZ,COSAUTLAN DE CARVAJAL
8,MÉXICO,VERACRUZ,COSCOMATEPEC
34,MÉXICO,VERACRUZ,COTAXTLA
1,MÉXICO,VERACRUZ,CUICHAPA
5,MÉXICO,VERACRUZ,CUITLAHUAC
152,MÉXICO,VERACRUZ,CHACALTIANGUIS
1,MÉXICO,VERACRUZ,LAS CHOAPAS
5,MÉXICO,VERACRUZ,CHOCAMAN
42,MÉXICO,VERACRUZ,EMILIANO ZAPATA
48,MÉXICO,VERACRUZ,FORTIN
20,MÉXICO,VERACRUZ,HUATUSCO
5,MÉXICO,VERACRUZ,HUEYAPAN DE OCAMPO
37,MÉXICO,VERACRUZ,HUILOAPAN DE CUAUHTEMOC
15,MÉXICO,VERACRUZ,IGNACIO DE LA LLAVE
233,MÉXICO,VERACRUZ,ISLA
1,MÉXICO,VERACRUZ,IXHUACAN DE LOS REYES
9,MÉXICO,VERACRUZ,IXHUATLAN DEL CAFE
98,MÉXICO,VERACRUZ,IXHUATLANCILLO
1,MÉXICO,VERACRUZ,IXHUATLAN DEL SURESTE
12,MÉXICO,VERACRUZ,IXMATLAHUACAN
386,MÉXICO,VERACRUZ,IXTACZOQUITLAN
17,MÉXICO,VERACRUZ,JALACINGO
297,MÉXICO,VERACRUZ,XALAPA
2,MÉXICO,VERACRUZ,JALCOMULCO
105,MÉXICO,VERACRUZ,JAMAPA
1,MÉXICO,VERACRUZ,JESUS CARRANZA
36,MÉXICO,VERACRUZ,XICO
5,MÉXICO,VERACRUZ,JILOTEPEC
225,MÉXICO,VERACRUZ,JUAN RODRIGUEZ CLARA
1,MÉXICO,VERACRUZ,LANDERO Y COSS
2,MÉXICO,VERACRUZ,LERDO DE TEJADA
11,MÉXICO,VERACRUZ,MAGDALENA
46,MÉXICO,VERACRUZ,MALTRATA
53,MÉXICO,VERACRUZ,MANLIO FABIO ALTAMIRANO
258,MÉXICO,VERACRUZ,MARIANO ESCOBEDO
12,MÉXICO,VERACRUZ,MARTINEZ DE LA TORRE
278,MÉXICO,VERACRUZ,MEDELLIN DE BRAVO
1,MÉXICO,VERACRUZ,MIAHUATLAN
13,MÉXICO,VERACRUZ,MINATITLAN
3,MÉXICO,VERACRUZ,MISANTLA
3,MÉXICO,VERACRUZ,MIXTLA DE ALTAMIRANO
6,MÉXICO,VERACRUZ,NAOLINCO
1,MÉXICO,VERACRUZ,NARANJAL
115,MÉXICO,VERACRUZ,NOGALES
6,MÉXICO,VERACRUZ,OMEALCA
677,MÉXICO,VERACRUZ,ORIZABA
58,MÉXICO,VERACRUZ,OTATITLAN
2,MÉXICO,VERACRUZ,PANUCO
3,MÉXICO,VERACRUZ,PAPANTLA
91,MÉXICO,VERACRUZ,PASO DEL MACHO
19,MÉXICO,VERACRUZ,PASO DE OVEJAS
73,MÉXICO,VERACRUZ,LA PERLA
8,MÉXICO,VERACRUZ,PEROTE
191,MÉXICO,VERACRUZ,PLAYA VICENTE
73,MÉXICO,VERACRUZ,PUENTE NACIONAL
65,MÉXICO,VERACRUZ,RAFAEL DELGADO
1,MÉXICO,VERACRUZ,RAFAEL LUCIO
235,MÉXICO,VERACRUZ,RIO BLANCO
23,MÉXICO,VERACRUZ,SAN ANDRES TENEJAPAN
4,MÉXICO,VERACRUZ,SAN ANDRES TUXTLA
7,MÉXICO,VERACRUZ,SAN JUAN EVANGELISTA
1,MÉXICO,VERACRUZ,SAYULA DE ALEMAN
1,MÉXICO,VERACRUZ,SOCHIAPA
14,MÉXICO,VERACRUZ,SOLEDAD ATZOMPA
53,MÉXICO,VERACRUZ,SOLEDAD DE DOBLADO
1,MÉXICO,VERACRUZ,TANTOYUCA
1,MÉXICO,VERACRUZ,TECOLUTLA
1,MÉXICO,VERACRUZ,TEHUIPANGO
28,MÉXICO,VERACRUZ,TEOCELO
2,MÉXICO,VERACRUZ,TEPATLAXCO
2,MÉXICO,VERACRUZ,TEPETLAN
16,MÉXICO,VERACRUZ,TEQUILA
618,MÉXICO,VERACRUZ,JOSE AZUETA
5,MÉXICO,VERACRUZ,TEXHUACAN
25,MÉXICO,VERACRUZ,TEZONAPA
3072,MÉXICO,VERACRUZ,TIERRA BLANCA
58,MÉXICO,VERACRUZ,TLACOJALPAN
1,MÉXICO,VERACRUZ,TLACOLULAN
2,MÉXICO,VERACRUZ,TLACOTALPAN
69,MÉXICO,VERACRUZ,TLALIXCOYAN
3,MÉXICO,VERACRUZ,TLALNELHUAYOCAN
12,MÉXICO,VERACRUZ,TLAQUILPA
22,MÉXICO,VERACRUZ,TLILAPAN
2,MÉXICO,VERACRUZ,TOMATLAN
2,MÉXICO,VERACRUZ,TUXPAN
8,MÉXICO,VERACRUZ,TUXTILLA
138,MÉXICO,VERACRUZ,URSULO GALVAN
10,MÉXICO,VERACRUZ,VEGA DE ALATORRE
1889,MÉXICO,VERACRUZ,VERACRUZ
2,MÉXICO,VERACRUZ,XOXOCOTLA
1,MÉXICO,VERACRUZ,YANGA
27,MÉXICO,VERACRUZ,ZENTLA
136,MÉXICO,VERACRUZ,ZONGOLICA
738,MÉXICO,VERACRUZ,TRES VALLES
196,MÉXICO,VERACRUZ,CARLOS A. CARRILLO
7,MÉXICO,VERACRUZ,UXPANAPA
1,MÉXICO,VERACRUZ,SAN RAFAEL
5,MÉXICO,VERACRUZ,SANTIAGO SOCHIAPAN
29,MÉXICO,YUCATÁN,ABALA
586,MÉXICO,YUCATÁN,ACANCEH
47,MÉXICO,YUCATÁN,AKIL
2,MÉXICO,YUCATÁN,BACA
16,MÉXICO,YUCATÁN,BOKOBA
40,MÉXICO,YUCATÁN,BUCTZOTZ
15,MÉXICO,YUCATÁN,CACALCHEN
167,MÉXICO,YUCATÁN,CALOTMUL
5,MÉXICO,YUCATÁN,CANSAHCAB
5,MÉXICO,YUCATÁN,CANTAMAYEC
234,MÉXICO,YUCATÁN,CELESTUN
1353,MÉXICO,YUCATÁN,CENOTILLO
12,MÉXICO,YUCATÁN,CONKAL
58,MÉXICO,YUCATÁN,CUNCUNUL
52,MÉXICO,YUCATÁN,CUZAMA
1,MÉXICO,YUCATÁN,CHACSINKIN
231,MÉXICO,YUCATÁN,CHANKOM
27,MÉXICO,YUCATÁN,CHAPAB
2168,MÉXICO,YUCATÁN,CHEMAX
1,MÉXICO,YUCATÁN,CHICXULUB PUEBLO
210,MÉXICO,YUCATÁN,CHICHIMILA
213,MÉXICO,YUCATÁN,CHIKINDZONOT
14,MÉXICO,YUCATÁN,CHOCHOLA
4,MÉXICO,YUCATÁN,CHUMAYEL
76,MÉXICO,YUCATÁN,DZAN
2,MÉXICO,YUCATÁN,DZEMUL
3,MÉXICO,YUCATÁN,DZIDZANTUN
33,MÉXICO,YUCATÁN,DZILAM DE BRAVO
11,MÉXICO,YUCATÁN,DZILAM GONZALEZ
401,MÉXICO,YUCATÁN,DZITAS
54,MÉXICO,YUCATÁN,DZONCAUICH
2164,MÉXICO,YUCATÁN,ESPITA
1,MÉXICO,YUCATÁN,HALACHO
772,MÉXICO,YUCATÁN,HOCABA
535,MÉXICO,YUCATÁN,HOCTUN
44,MÉXICO,YUCATÁN,HOMUN
23,MÉXICO,YUCATÁN,HUHI
107,MÉXICO,YUCATÁN,HUNUCMA
2,MÉXICO,YUCATÁN,IXIL
3395,MÉXICO,YUCATÁN,IZAMAL
152,MÉXICO,YUCATÁN,KANASIN
318,MÉXICO,YUCATÁN,KANTUNIL
155,MÉXICO,YUCATÁN,KAUA
39,MÉXICO,YUCATÁN,KINCHIL
2,MÉXICO,YUCATÁN,KOPOMA
3,MÉXICO,YUCATÁN,MAMA
71,MÉXICO,YUCATÁN,MANI
41,MÉXICO,YUCATÁN,MAXCANU
17,MÉXICO,YUCATÁN,MAYAPAN
1382,MÉXICO,YUCATÁN,MERIDA
54,MÉXICO,YUCATÁN,MOTUL
46,MÉXICO,YUCATÁN,MUNA
5,MÉXICO,YUCATÁN,MUXUPIP
4,MÉXICO,YUCATÁN,OPICHEN
263,MÉXICO,YUCATÁN,OXKUTZCAB
1393,MÉXICO,YUCATÁN,PANABA
16,MÉXICO,YUCATÁN,PETO
46,MÉXICO,YUCATÁN,PROGRESO
255,MÉXICO,YUCATÁN,QUINTANA ROO
547,MÉXICO,YUCATÁN,RIO LAGARTOS
35,MÉXICO,YUCATÁN,SACALUM
83,MÉXICO,YUCATÁN,SAMAHIL
8,MÉXICO,YUCATÁN,SANAHCAT
347,MÉXICO,YUCATÁN,SAN FELIPE
16,MÉXICO,YUCATÁN,SANTA ELENA
237,MÉXICO,YUCATÁN,SEYE
1,MÉXICO,YUCATÁN,SINANCHE
35,MÉXICO,YUCATÁN,SOTUTA
313,MÉXICO,YUCATÁN,SUCILA
211,MÉXICO,YUCATÁN,SUDZAL
3,MÉXICO,YUCATÁN,SUMA
296,MÉXICO,YUCATÁN,TAHMEK
66,MÉXICO,YUCATÁN,TEABO
148,MÉXICO,YUCATÁN,TECOH
485,MÉXICO,YUCATÁN,TEKAL DE VENEGAS
218,MÉXICO,YUCATÁN,TEKANTO
193,MÉXICO,YUCATÁN,TEKAX
47,MÉXICO,YUCATÁN,TEKIT
110,MÉXICO,YUCATÁN,TEKOM
1,MÉXICO,YUCATÁN,TELCHAC PUEBLO
34,MÉXICO,YUCATÁN,TEMAX
421,MÉXICO,YUCATÁN,TEMOZON
270,MÉXICO,YUCATÁN,TEPAKAN
7,MÉXICO,YUCATÁN,TETIZ
226,MÉXICO,YUCATÁN,TEYA
748,MÉXICO,YUCATÁN,TICUL
44,MÉXICO,YUCATÁN,TIMUCUY
1848,MÉXICO,YUCATÁN,TINUM
145,MÉXICO,YUCATÁN,TIXCACALCUPUL
30,MÉXICO,YUCATÁN,TIXKOKOB
4,MÉXICO,YUCATÁN,TIXMEHUAC
3,MÉXICO,YUCATÁN,TIXPEHUAL
3210,MÉXICO,YUCATÁN,TIZIMIN
1368,MÉXICO,YUCATÁN,TUNKAS
9,MÉXICO,YUCATÁN,TZUCACAB
221,MÉXICO,YUCATÁN,UAYMA
9,MÉXICO,YUCATÁN,UCU
785,MÉXICO,YUCATÁN,UMAN
3152,MÉXICO,YUCATÁN,VALLADOLID
296,MÉXICO,YUCATÁN,XOCCHEL
366,MÉXICO,YUCATÁN,YAXCABA
1,MÉXICO,YUCATÁN,YAXKUKUL
1,MÉXICO,YUCATÁN,YOBAIN
1,MÉXICO,ZACATECAS,NOCHISTLAN DE MEJIA
1,MÉXICO,ZACATECAS,TEPECHITLAN
2,MÉXICO,QUINTANA ROO,QUINTANA ROO
1,ESTADOS UNIDOS,NEW JERSEY,MINOTOLA
